name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  AWS_ACCOUNT_ID: 311535938619

permissions:
  id-token: write
  contents: read

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run export

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::311535938619:role/BlintestGithubRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync ./dist s3://blindtest-playlists
